# Makefile for Linux samples code
KBUILD_CFLAGS += -Werror -Wno-format-truncation
obj-$(CONFIG_SAMPLES)	+= kobject/ kprobes/ trace_events/ livepatch/ \
			   hw_breakpoint/ kfifo/ kdb/ hidraw/ rpmsg/ seccomp/ \
			   configfs/ qmi/
